//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanaTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sana_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sana_Order()
        {
            this.Sana_ProductOrder = new HashSet<Sana_ProductOrder>();
        }
    
        public long idOrder { get; set; }
        public System.DateTime creationDate { get; set; }
        public long idCustomer { get; set; }
    
        public virtual Sana_Customer Sana_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sana_ProductOrder> Sana_ProductOrder { get; set; }
    }
}
