//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanaTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sana_CategorieAndProduct
    {
        public long idProduct { get; set; }
        public long idCategorie { get; set; }
        public System.DateTime creationDate { get; set; }
    
        public virtual Sana_Product Sana_Product { get; set; }
        public virtual Sana_ProductCategorie Sana_ProductCategorie { get; set; }
    }
}
