//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanaTest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SanaEntities : DbContext
    {
        public SanaEntities()
            : base("name=SanaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Sana_CategorieAndProduct> Sana_CategorieAndProduct { get; set; }
        public virtual DbSet<Sana_Customer> Sana_Customer { get; set; }
        public virtual DbSet<Sana_Order> Sana_Order { get; set; }
        public virtual DbSet<Sana_Product> Sana_Product { get; set; }
        public virtual DbSet<Sana_ProductCategorie> Sana_ProductCategorie { get; set; }
        public virtual DbSet<Sana_ProductOrder> Sana_ProductOrder { get; set; }
    }
}
