//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SanaTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sana_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sana_Product()
        {
            this.Sana_CategorieAndProduct = new HashSet<Sana_CategorieAndProduct>();
            this.Sana_ProductOrder = new HashSet<Sana_ProductOrder>();
        }
    
        public long idProduct { get; set; }
        public string title { get; set; }
        public decimal price { get; set; }
        public long productNumber { get; set; }
        public System.DateTime creationDate { get; set; }
        public Nullable<System.DateTime> modificationDate { get; set; }
        public bool bit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sana_CategorieAndProduct> Sana_CategorieAndProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sana_ProductOrder> Sana_ProductOrder { get; set; }
    }
}
